apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-test-depl
  labels:
    app: quarkus-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-test
  template:
    metadata:
      labels:
        app: quarkus-test
    spec:
      containers:
      - name: quarkus-test
        image: docker.io/domenicopiol/quarkus-test:latest
        command: ["./application"]
        args: ["-Dquarkus.http.host=0.0.0.0"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-test-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: quarkus-test
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: quarkus-test-route
spec:
  port:
    targetPort: 8080
  wildcardPolicy: None
  to:
    kind: Service
    name: quarkus-test-service
    weight: 100